name: Build packages
on: push

jobs:
    main:
        env:
            PACKAGE: ${{ matrix.PKGS }}
            OBS_AUTH: ${{ secrets.OBS_AUTH }}
            OBS_PROJECT: ${{ secrets.OBS_PROJECT }}
        runs-on: ubuntu-20.04
        container:
            image: justkdng/archlinux
        strategy:
            matrix:
                PKGS: ["ungoogled-chromium", "ungoogled-chromium-ozone"]
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Prepare environment
              run: .github/workflows/env
            - name: Run prepare()
              run: sudo -u build -H bash -c .github/workflows/prepare
            - name: Trigger OBS build
              run: .github/workflows/obs_trigger

